# Generated by Django 2.0.2 on 2019-11-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255)),
                ('p_desc', models.TextField()),
                ('p_price', models.CharField(max_length=255)),
                ('p_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('image', models.ImageField(upload_to='')),
                ('p_c_name', models.ForeignKey(on_delete=True, to='product.Category')),
            ],
        ),
    ]
